[package]
name = "rust-bloom"
version = "1.0.0"
authors = ["faruken"]
description = "A simple bloom filter implementation that uses farmhash"
repository = "https://github.com/faruken/rust-bloom"
license = "MIT"

[lib]
name="bloom"
path="src/bloom/mod.rs"

[dependencies]
farmhash = "1.1.5"
